version: '3.8'

services:
  app:
    build: .
    container_name: flight-finder-app-qa
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: qa
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${APP_PORT}:8080"

x-project-name: &project-name flight-finder-app-qa

