spring.application.name=flight-finder-ms-db

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:flight_finder_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:admin}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configurationnn
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# SerpApi Configuration
serpapi.api.key=c407df6dedb437bf00a6d7d5fb518d1195403a309b6fc2231e82646d16f45718
serpapi.base.url=https://serpapi.com